### ISSUE TITLE
Test the new compression features especially for retrieval

### ISSUE THREAD

**Issue by phax** [phax/as2-server#11]
Based on issue #9 

Test the new compression featured added in version 2.1.0.
The following uses cases existing from the top of my head:
  * Compress, no encryption, no signing
  * Compress, no encryption, signing - compress before sign
  * Compress, no encryption, signing - compress after sign
  * Compress, encryption, no signing
  * Compress, encryption, signing - compress before sign
  * Compress, encryption, signing - compress after sign

The following things should be tested:
  * Is the decrypted/decompress content the same as the sent one
  * Is the calculated MIC identical to the send one and if not, which one is wrong? (sending MICs have been validated with Mendelson Test Server, but only for encrypted and signed messages)

**Comment by MReinigJr** [comment]
No problem.  :)

I should be able to get to this over the weekend.

**Comment by phax** [comment]
Hi Michael!
Do you have any update for me?
// Philip

**Comment by phax** [comment]
Any update or shall I close it?

**Comment by MReinigJr** [comment]
Hi Philip,

Very sorry, but no.  I do still have plans on getting to this, but not until my company expands our EDI capabilities, which should be near the end of the year or slightly later...hopefully.  If you like, go ahead and close, and I can reopen if there is an issue.

Thanks,
Michael
