### ISSUE TITLE
Extend the documentation for usage of as2-lib/as2-server

### ISSUE THREAD

**Issue by phax** [phax/as2-server#12]
Based on issue #9 

Currently the documentation quality and quantity is quite poor.
Therefore additional documentation on
  * Building
  * Configuration
  * Supported use cases
  * ...

would be very helpful

**Comment by MReinigJr** [comment]
Hi Philip,

Sounds great.  I can definitely improve this.  Question though.  While coming across the problem noted in #14, I realized that I don't know how the resend feature works.  Can you please explain this?

Thanks,
Michael

**Comment by phax** [comment]
Hi Michael!
Do you still have plans on This?
// Philip

**Comment by MReinigJr** [comment]
Hi Philip,

I do still have plans on getting to this, but not until my company expands our EDI capabilities, which should be near the end of the year or slightly later...hopefully.  If you like, go ahead and close, and I can reopen at that time.

Thanks,
Michael

**Comment by phax** [comment]
Thanks for the update :)
