### ISSUE TITLE
Unencrypted Connection for Health Check

### ISSUE THREAD

**Issue by qudade** [phax/as2-server#19]
Hi,

first of all thanks for all the work you put into this project.

For our deployment we'd like to add some Health Check, i.e. some simple http call that returns Code 200 if the server is running (ideally, if running without issues).

We can find only encrypted modes of communication. Did we miss something? Is it possible to get e.g. some status or version information without the need to created encrypted and signed messages?

Best regards,

daki

**Comment by phax** [comment]
Hi daki,
well good question. The standalone server is not really extended, because I personally use it only in a servlet environment. And there you can easily ping stuff.
But if you have a PR that provides a "ping" (that should be customizable of course), I'm happy to integrate it :)
hth, Philip

**Comment by daten-kieker** [comment]
Hi phax,

your hint sounds interesting, but I can't find a good starting point on how to use/implement custom commands. Any pointers?

**Comment by phax** [comment]
I suggest switching to the Servlet based version. Than you can use Tomcat or Jetty for correct https support
