### ISSUE TITLE
"Signature is not a correct PKCS7 signature" when sending sync MDN

### ISSUE THREAD

**Issue by swienty1** [phax/as2-server#21]
Hi,

first of all thanks for all the work you put into this project, it's really amazing!

I have been testing your library (as2-server 4.0.2) against another AS2 product called RSSBUS. Sending files from your as2-server to RSSBUS work perfect but I have problem with receiving documents from RSSBUS and response with correct MDN (sync).

When I try to send a document to as2-server from RSSBUS I always receive:

"Response Details: The receipt signature could not be verified: Signature is not a correct PKCS7 signature."

What can be wrong? Where I made mistake? Any help would be appreciated.

Kind regards,
Maciej

**Comment by phax** [comment]
Very good question...  I have no idea. Can you enable improved logging in RSSBUS?

**Comment by swienty1** [comment]
Hello again,

sorry for the delay in answer. I attach two zip files:
-as2.zip contains configuration files and exchange documents from a perspective of your as2 server;
-rssbus.zip contains files from rssbus perspective.

Both files contain certificates used to exchange communication.

[rssbus.zip](https://github.com/phax/as2-server/files/1979121/rssbus.zip)
[as2.zip](https://github.com/phax/as2-server/files/1979122/as2.zip)
