### ISSUE TITLE
When using largefileon=true MIC isn't matched when using sign,encrypt and compress

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-server#25]
Hi Philip,
The new setting largefileon=true cause the MIC to be not matched.
When you remove this attribute from confix.xml it succeeded.
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi Philip,
see Issue #78 - in as2-lib
Ziv Harpaz had the fix for this but you didn't approve the pull request.
Thanks,
Itay

**Comment by phax** [comment]
Fixed for 4.3.0
